name: Set up Godot
description: Set up Godot engine for building and exporting
inputs:
  godot-version:
    description: 'Godot version to use'
    required: true
  godot-release:
    description: 'Godot release type (stable/rc/beta/alpha)'
    required: true
runs:
  using: composite
  steps:
    - name: Make folders
      shell: bash
      run: |
        mkdir -v -p ~/godot
    - name: Use cache
      id: godot-cache
      uses: actions/cache@v4
      with:
        key: ${{ inputs.godot-version }}-${{ inputs.godot-release }}
        path: |
          ~/godot
    - name: Download Godot
      if: steps.godot-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget -q https://github.com/godotengine/godot-builds/releases/download/${{ inputs.godot-version }}-${{ inputs.godot-release }}/Godot_v${{ inputs.godot-version }}-${{ inputs.godot-release }}_linux.x86_64.zip
        unzip Godot_v${{ inputs.godot-version }}-${{ inputs.godot-release }}_linux.x86_64.zip -d ~
        mv ~/Godot_v${{ inputs.godot-version }}-${{ inputs.godot-release }}_linux.x86_64 ~/godot/godot
    - name: Add Godot to path
      shell: bash
      run: echo "~/godot" >> $GITHUB_PATH
