name: export-optimized
on:
  pull_request:
    branches: [ main ]
env:
  GODOT_VERSION: 4.3
  PROJECT_NAME: GodSVG
  GODOT_REPO: https://github.com/godotengine/godot.git
  GODOT_COMMIT_HASH: 77dcf97
  BUILD_OPTIONS: target=template_release lto=full production=yes deprecated=no minizip=no brotli=no vulkan=no openxr=no use_volk=no disable_3d=yes modules_enabled_by_default=no module_freetype_enabled=yes module_gdscript_enabled=yes module_svg_enabled=yes module_jpg_enabled=yes module_text_server_adv_enabled=yes graphite=no module_webp_enabled=yes
jobs:
  build-and-export:
    name: Build and Export for ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
            preset: "Linux/X11"
            artifact: GodSVG.x86_64
          - platform: windows
            os: ubuntu-latest
            preset: "Windows Desktop"
            artifact: GodSVG.exe
          - platform: macos
            os: macos-latest
            preset: "macOS"
            artifact: GodSVG.zip
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies (Linux/Windows)
        if: matrix.platform == 'linux' || matrix.platform == 'windows'
        run: |
          sudo apt update
          sudo apt install -y scons python3
          if [ "${{ matrix.platform }}" = "windows" ]; then
            sudo apt install -y g++-mingw-w64-x86-64-posix wine64
          fi
      - name: Install dependencies (macOS)
        if: matrix.platform == 'macos'
        run: brew install scons
      - name: Clone Godot repository
        run: git clone $GODOT_REPO godot
      - name: Checkout specific commit
        run: |
          cd godot
          git fetch
          git checkout $GODOT_COMMIT_HASH
      - name: Build Godot (Linux)
        if: matrix.platform == 'linux'
        run: |
          cd godot
          scons p=linuxbsd arch=x86_64 optimize=speed ${BUILD_OPTIONS}
      - name: Build Godot (Windows)
        if: matrix.platform == 'windows'
        run: |
          cd godot
          scons p=windows target=template_release tools=no ${BUILD_OPTIONS}
      - name: Build Godot (macOS)
        if: matrix.platform == 'macos'
        run: |
          cd godot
          scons p=macos arch=arm64 optimize=speed ${BUILD_OPTIONS}
          scons p=macos arch=x86_64 optimize=speed ${BUILD_OPTIONS}
          cd bin
          lipo -create godot.macos.template_release.x86_64 godot.macos.template_release.arm64 -output godot.macos.template_release.universal
          chmod +x *
          cp -R ../misc/dist/macos_template.app .
          mkdir -p macos_template.app/Contents/MacOS
          cp godot.macos.template_release.universal macos_template.app/Contents/MacOS/godot_macos_release.universal
          chmod +x macos_template.app/Contents/MacOS/godot_macos*
      - name: Export project
        run: |
          mkdir -p build
          if [ "${{ matrix.platform }}" = "linux" ]; then
            ./godot/bin/godot.linuxbsd.template_release.x86_64 --headless --export-release "${{ matrix.preset }}" build/${{ matrix.artifact }}
          elif [ "${{ matrix.platform }}" = "windows" ]; then
            wine64 ./godot/bin/godot.windows.template_release.x86_64.exe --headless --export-release "${{ matrix.preset }}" build/${{ matrix.artifact }}
          elif [ "${{ matrix.platform }}" = "macos" ]; then
            ./godot/bin/macos_template.app/Contents/MacOS/godot_macos_release.universal --headless --export-release "${{ matrix.preset }}" build/${{ matrix.artifact }}
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-${{ matrix.platform }}
          path: build/${{ matrix.artifact }}
          if-no-files-found: error
          retention-days: 28
